AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'lib/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
Layout/AlignHash:
  Enabled: false
Layout/EmptyLines:
  Enabled: true
  Exclude:
    - 'Gemfile'
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: true
  Exclude:
    - 'db/migrate/*'
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  Exclude:
    - 'config/**/*'
Metrics/LineLength:
  Enabled: true
  Max:     120
  Exclude:
    - 'config/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment: 
  Enabled: false
Style/StringLiterals:
  Enabled: false
